'use server';

/**
 * @fileOverview Generates a block of text for a given topic using an AI model.
 *
 * - generateTextBlock - A function that generates a block of text.
 * - GenerateTextBlockInput - The input type for the generateTextBlock function.
 * - GenerateTextBlockOutput - The return type for the generateTextBlock function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateTextBlockInputSchema = z.object({
  topic: z
    .string()
    .describe('The topic or prompt to generate a text block for.'),
});
export type GenerateTextBlockInput = z.infer<typeof GenerateTextBlockInputSchema>;

const GenerateTextBlockOutputSchema = z.object({
  textBlock: z
    .string()
    .describe('A block of text generated by the AI.'),
});
export type GenerateTextBlockOutput = z.infer<typeof GenerateTextBlockOutputSchema>;

export async function generateTextBlock(input: GenerateTextBlockInput): Promise<GenerateTextBlockOutput> {
  return generateTextBlockFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateTextBlockPrompt',
  input: {schema: GenerateTextBlockInputSchema},
  output: {schema: GenerateTextBlockOutputSchema},
  prompt: `Anda adalah seorang copywriter profesional yang ahli dalam menyusun teks yang menarik dan informatif untuk halaman web.

  Tulis sebuah paragraf singkat (2-3 kalimat) berdasarkan topik atau instruksi berikut. Pastikan teksnya jelas, ringkas, dan cocok untuk sebuah landing page.

  Topik: {{{topic}}}`,
});

const generateTextBlockFlow = ai.defineFlow(
  {
    name: 'generateTextBlockFlow',
    inputSchema: GenerateTextBlockInputSchema,
    outputSchema: GenerateTextBlockOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
